# Generated by Django 5.2.13 on 2026-04-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=20)),
                ('quantity', models.FloatField()),
                ('total_cost', models.FloatField()),
                ('cost_per_unit', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
