# Generated by Django 5.2.13 on 2026-04-30 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0002_recipe_recipeingredient'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cookies_produced', models.IntegerField()),
                ('utilities_cost', models.FloatField(default=0)),
                ('labor_cost', models.FloatField(default=0)),
                ('total_cost', models.FloatField(default=0)),
                ('produced_at', models.DateTimeField(auto_now_add=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bakery.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Packaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_type', models.CharField(choices=[('zipper', 'Zipper Bag'), ('tin', 'Tin')], max_length=20)),
                ('quantity', models.IntegerField()),
                ('cookies_per_package', models.IntegerField()),
                ('packaging_cost', models.FloatField(default=0)),
                ('production_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='bakery.productionbatch')),
            ],
        ),
    ]
